package com.varzagus.fow;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import java.util.HashMap;
import java.util.Map;

public class SeleniumTests {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:/WebDriver/bin/geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void test1() throws InterruptedException {
        driver.get("http://localhost:8080/login");
        driver.manage().window().setSize(new Dimension(1920, 1002));
        driver.findElement(By.name("username")).click();
        driver.findElement(By.name("username")).sendKeys("admin");
        driver.findElement(By.id("usernameForm")).click();
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("123");
        driver.findElement(By.cssSelector(".form-group:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".accent")).click();
        driver.findElement(By.cssSelector(".accent:nth-child(1)")).click();
        driver.findElement(By.linkText("Вопросы")).click();
        driver.findElement(By.linkText("Добавить вопрос")).click();
        driver.findElement(By.linkText("Вернуться")).click();
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > a")).click();
        driver.findElement(By.linkText("Вернуться")).click();
        driver.findElement(By.linkText("Вернуться")).click();
        driver.findElement(By.linkText("Пользователи")).click();
        driver.findElement(By.linkText("Редактировать")).click();
        driver.findElement(By.linkText("Вернуться")).click();
        driver.findElement(By.linkText("Добавить пользователя")).click();
        driver.findElement(By.linkText("Вернуться")).click();
        driver.findElement(By.linkText("Вернуться")).click();
        driver.findElement(By.linkText("admin")).click();
        driver.findElement(By.linkText("Вернуться")).click();
    }
}
